<a href="https://colab.research.google.com/github/bhattacharya5/DeepLearning/blob/main/DL_MtechEx_tensors_basics_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**NOTE :** The tutorial is collected from online resources


i. https://cs231n.github.io/convolutional-networks/
ii. https://medium.datadriveninvestor.com/convolutional-neural-network-cnn-simplified-ecafd4ee52c5
iii. https://www.simplilearn.com/tutorials/deep-learning-tutorial/rnn
iv. https://colah.github.io/posts/2015-08-Understanding-LSTMs/
v. https://towardsdatascience.com/how-the-lstm-improves-the-rnn-1ef156b75121

1. For learning Pytorch - https://youtube.com/playlist?list=PLqnslRFeH2UrcDBWF5mfPGpqQDSta6VK4
2. For optimizers - https://youtu.be/TudQZtgpoHk

Let's import the `torch` module to get started.

In [ ]:
import torch

In [ ]:
torch.cuda.is_available()

True

## Tensors

At its core, PyTorch is a library for processing tensors. A tensor is a number, vector, matrix, or any n-dimensional array. Let's create a tensor with a single number.

In [ ]:
# Number
t1 = torch.tensor(4, dtype=torch.float64)
print(t1)
print(t1.shape)
print(t1.dtype)

tensor(4., dtype=torch.float64)
torch.Size([])
torch.float64


In [ ]:
z = torch.zeros((5, 3), dtype=torch.int16)
print(z)
print(z.dtype)
print(z.shape)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]], dtype=torch.int16)
torch.int16
torch.Size([5, 3])


Let's try creating more complex tensors.

In [ ]:
# Vector
t2 = torch.tensor([1., 2, 3, 4])
print(t2)
print(t2.dtype)
print(t2.shape)

tensor([1., 2., 3., 4.])
torch.float32
torch.Size([4])


In [ ]:
# Vector
t2 = torch.tensor(([1, 2, 3, 4]),dtype=torch.int16)
t2
print(t2.dtype)
t2.shape

torch.int16


torch.Size([4])

In [ ]:
t10 = torch.tensor([1,3])
t10

tensor([1, 3])

In [ ]:
# Matrix
t3 = torch.tensor([[5., 6,8], 
                   [7, 8,7], 
                   [9, 10,6]])
t3

tensor([[ 5.,  6.,  8.],
        [ 7.,  8.,  7.],
        [ 9., 10.,  6.]])

In [ ]:
t3.dtype

torch.float32

In [ ]:
t3.shape

torch.Size([3, 3])

In [ ]:
# 3-dimensional array
t4 = torch.tensor([
    [[11, 12, 13], 
     [13, 14, 15]], 
    [[15, 16, 17], 
     [17, 18, 19.]]])
print(t4.shape)
t4

torch.Size([2, 2, 3])


tensor([[[11., 12., 13.],
         [13., 14., 15.]],

        [[15., 16., 17.],
         [17., 18., 19.]]])

In [ ]:
torch.manual_seed(1729)
r1 = torch.rand(2, 2)
print('A random tensor:')
print(r1)

r2 = torch.rand(2, 2)
print('\nA different random tensor:')
print(r2) # new values

torch.manual_seed(1729)
r3 = torch.rand(2, 2 ,3)

print(r3)

A random tensor:
tensor([[0.3126, 0.3791],
        [0.3087, 0.0736]])

A different random tensor:
tensor([[0.4216, 0.0691],
        [0.2332, 0.4047]])
tensor([[[0.3126, 0.3791, 0.3087],
         [0.0736, 0.4216, 0.0691]],

        [[0.2332, 0.4047, 0.2162],
         [0.9927, 0.4128, 0.5938]]])


Note that it's not possible to create tensors with an improper shape.

In [ ]:
# Matrix
t5 = torch.tensor([[5., 6, 11], 
                   [7, 8,8], 
                   [9, 10,7]])
t5

tensor([[ 5.,  6., 11.],
        [ 7.,  8.,  8.],
        [ 9., 10.,  7.]])

A `ValueError` is thrown because the lengths of the rows `[5., 6, 11]` and `[7, 8]` don't match.

## Tensor operations and gradients

We can combine tensors with the usual arithmetic operations. Let's look at an example:

In [ ]:
# Create tensors.
x = torch.tensor(3.)
w = torch.tensor(4., requires_grad=True)
b = torch.tensor(5., requires_grad=True)
x, w, b

(tensor(3.), tensor(4., requires_grad=True), tensor(5., requires_grad=True))

In [ ]:
# Arithmetic operations
y = w * x + b
y

tensor(17., grad_fn=<AddBackward0>)

In [ ]:
r = (torch.rand(2, 2) - 0.5) * 2 # values between -1 and 1
print('A random matrix, r:')
print(r)

# Common mathematical operations are supported:
print('\nAbsolute value of r:')
print(torch.abs(r))

# ...as are trigonometric functions:
print('\nInverse sine of r:')
print(torch.asin(r))

# ...and linear algebra operations like determinant and singular value decomposition
print('\nDeterminant of r:')
print(torch.det(r))
print('\nSingular value decomposition of r:')
print(torch.svd(r))

# ...and statistical and aggregate operations:
print('\nAverage and standard deviation of r:')
print(torch.std_mean(r))
print('\nMaximum value of r:')
print(torch.max(r))

A random matrix, r:
tensor([[ 0.2255, -0.6961],
        [-0.9093,  0.0070]])

Absolute value of r:
tensor([[0.2255, 0.6961],
        [0.9093, 0.0070]])

Inverse sine of r:
tensor([[ 0.2275, -0.7700],
        [-1.1417,  0.0070]])

Determinant of r:
tensor(-0.6314)

Singular value decomposition of r:
torch.return_types.svd(
U=tensor([[-0.4635,  0.8861],
        [ 0.8861,  0.4635]]),
S=tensor([0.9679, 0.6524]),
V=tensor([[-0.9405, -0.3398],
        [ 0.3398, -0.9405]]))

Average and standard deviation of r:
(tensor(0.5450), tensor(-0.3432))

Maximum value of r:
tensor(0.2255)


In [ ]:
# Compute derivatives
y.backward()

The derivatives of `y` with respect to the input tensors are stored in the `.grad` property of the respective tensors.

In [ ]:
# Display gradients
print('dy/dx:', x.grad)
print('dy/dw:', w.grad)
print('dy/db:', b.grad)

dy/dx: None
dy/dw: tensor(3.)
dy/db: tensor(1.)


As expected, `dy/dw` has the same value as `x`, i.e., `3`, and `dy/db` has the value `1`. Note that `x.grad` is `None` because `x` doesn't have `requires_grad` set to `True`. 

The "grad" in `w.grad` is short for _gradient_, which is another term for derivative. The term _gradient_ is primarily used while dealing with vectors and matrices.

## Tensor functions

Apart from arithmetic operations, the `torch` module also contains many functions for creating and manipulating tensors. Let's look at some examples.

In [ ]:
# Create a tensor with a fixed value for every element
t6 = torch.full((3, 3), 42)
t6


tensor([[42, 42, 42],
        [42, 42, 42],
        [42, 42, 42]])

In [ ]:
# Concatenate two tensors with compatible shapes
t7 = torch.cat((t3, t6))
t7

tensor([[ 5.,  6.,  8.],
        [ 7.,  8.,  7.],
        [ 9., 10.,  6.],
        [42., 42., 42.],
        [42., 42., 42.],
        [42., 42., 42.]])

In [ ]:
# Compute the sin of each element
t8 = torch.sin(t7)
t8

tensor([[-0.9589, -0.2794,  0.9894],
        [ 0.6570,  0.9894,  0.6570],
        [ 0.4121, -0.5440, -0.2794],
        [-0.9165, -0.9165, -0.9165],
        [-0.9165, -0.9165, -0.9165],
        [-0.9165, -0.9165, -0.9165]])

In [ ]:
# Change the shape of a tensor
print(t8.shape)
print(t8)
t9 = t8.reshape(2,9)
print(t9.shape)
print(t9)

torch.Size([6, 3])
tensor([[-0.9589, -0.2794,  0.9894],
        [ 0.6570,  0.9894,  0.6570],
        [ 0.4121, -0.5440, -0.2794],
        [-0.9165, -0.9165, -0.9165],
        [-0.9165, -0.9165, -0.9165],
        [-0.9165, -0.9165, -0.9165]])
torch.Size([2, 9])
tensor([[-0.9589, -0.2794,  0.9894,  0.6570,  0.9894,  0.6570,  0.4121, -0.5440,
         -0.2794],
        [-0.9165, -0.9165, -0.9165, -0.9165, -0.9165, -0.9165, -0.9165, -0.9165,
         -0.9165]])


Here's how we create an array in Numpy:

In [ ]:
import numpy as np

x = np.array([[1, 2], [3, 4.]])
x

array([[1., 2.],
       [3., 4.]])

We can convert a Numpy array to a PyTorch tensor using `torch.from_numpy`.

In [ ]:
# Convert the numpy array to a torch tensor.
y = torch.from_numpy(x)
y

tensor([[1., 2.],
        [3., 4.]], dtype=torch.float64)

Let's verify that the numpy array and torch tensor have similar data types.

In [ ]:
x.dtype, y.dtype

(dtype('float64'), torch.float64)

We can convert a PyTorch tensor to a Numpy array using the `.numpy` method of a tensor.

In [ ]:
# Convert a torch tensor to a numpy array
z = y.numpy()
z

array([[1., 2.],
       [3., 4.]])